In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [31]:
dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

In [32]:
dataset

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [33]:
from sklearn.tree import DecisionTreeRegressor

regressor = DecisionTreeRegressor( random_state = 0)

regressor.fit(X,y)

regressor.predict([[6.5]])





array([150000.])

In [34]:
regressor.predict(X)

array([  45000.,   50000.,   60000.,   80000.,  110000.,  150000.,
        200000.,  300000.,  500000., 1000000.])

In [25]:
X

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [ ]:
X_grid =  np.arange( min(X) , max(X) , 0.1  )
X_grid = X_grid.reshape( len(X_grid), 1 )


plt.scatter( X, y )
# plt.plot( X, regressor.predict(X) ) 
plt.plot(X_grid, regressor.predict(X_grid)  )

/var/folders/15/p551z5bx22l9wb197m4k8bqm0000gn/T/ipykernel_4555/4093158623.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  X_grid =  np.arange( min(X) , max(X) , 0.1  )
