In [25]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [26]:
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values







In [27]:
dataset

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [28]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size =0.25 , random_state=0)


In [29]:
from sklearn.preprocessing import StandardScaler


sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [30]:
X_train , X_test

(array([[ 0.5816, -0.8867],
        [-0.6067,  1.4617],
        [-0.0125, -0.5678],
        [-0.6067,  1.8966],
        [ 1.3739, -1.4086],
        [ 1.4729,  0.9978],
        [ 0.0865, -0.7997],
        [-0.0125, -0.2489],
        [-0.2106, -0.5678],
        [-0.2106, -0.1909],
        [-0.3096, -1.2926],
        [-0.3096, -0.5678],
        [ 0.3836,  0.0991],
        [ 0.8787, -0.5968],
        [ 2.0671, -1.1766],
        [ 1.0768, -0.1329],
        [ 0.6807,  1.7807],
        [-0.7058,  0.563 ],
        [ 0.7797,  0.36  ],
        [ 0.8787, -0.5388],
        [-1.2009, -1.5825],
        [ 2.1662,  0.9399],
        [-0.0125,  1.2298],
        [ 0.1855,  1.0848],
        [ 0.3836, -0.4808],
        [-0.3096, -0.3068],
        [ 0.9778, -0.8287],
        [ 0.9778,  1.8676],
        [-0.0125,  1.2588],
        [-0.9038,  2.2735],
        [-1.2009, -1.5825],
        [ 2.1662, -0.7997],
        [-1.399 , -1.4666],
        [ 0.3836,  2.3025],
        [ 0.7797,  0.7659],
        [-1.0029, -0

In [31]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier( n_neighbors = 5,
                                   metric = 'minkowski' ,
                                   p =2  )


classifier.fit(X_train,y_train)


KNeighborsClassifier()

In [32]:
y_pred = classifier.predict(X_test)

In [33]:
from sklearn.metrics import confusion_matrix , accuracy_score


cm = confusion_matrix(y_test,y_pred)
print(cm)

accuracy_score(y_test,y_pred)

[[64  4]
 [ 3 29]]


0.93

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_train), y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.5),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.5))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(['#FA8072', '#1E90FF']))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(['#FA8072', '#1E90FF'])(i), label = j)
plt.title('K-NN (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

[[    44.  39000.]
 [    32. 120000.]
 [    38.  50000.]
 [    32. 135000.]
 [    52.  21000.]
 [    53. 104000.]
 [    39.  42000.]
 [    38.  61000.]
 [    36.  50000.]
 [    36.  63000.]
 [    35.  25000.]
 [    35.  50000.]
 [    42.  73000.]
 [    47.  49000.]
 [    59.  29000.]
 [    49.  65000.]
 [    45. 131000.]
 [    31.  89000.]
 [    46.  82000.]
 [    47.  51000.]
 [    26.  15000.]
 [    60. 102000.]
 [    38. 112000.]
 [    40. 107000.]
 [    42.  53000.]
 [    35.  59000.]
 [    48.  41000.]
 [    48. 134000.]
 [    38. 113000.]
 [    29. 148000.]
 [    26.  15000.]
 [    60.  42000.]
 [    24.  19000.]
 [    42. 149000.]
 [    46.  96000.]
 [    28.  59000.]
 [    39.  96000.]
 [    28.  89000.]
 [    41.  72000.]
 [    45.  26000.]
 [    33.  69000.]
 [    20.  82000.]
 [    31.  74000.]
 [    42.  80000.]
 [    35.  72000.]
 [    33. 149000.]
 [    40.  71000.]
 [    51. 146000.]
 [    46.  79000.]
 [    35.  75000.]
 [    38.  51000.]
 [    36.  75000.]
 [    37.  7

In [ ]:
from matplotlib.colors import ListedColormap

np.set_printoptions(precision=4 , suppress=True)

print(sc.inverse_transform(X_train))


X_set, y_set = sc.inverse_transform(X_test), y_test
X1, X2 = np.meshgrid(np.arange( start = X_set[:,0].min() -10 , stop= X_set[:,0].max() +10 , step=0.25 ),
                     np.arange( start = X_set[:,1].min() -1000 , stop=X_set[:,1].max() +1000 , step=0.25 )
                      )



plt.contourf(X1,X2, classifier.predict( sc.transform( np.array( [X1.ravel() , X2.ravel() ]).T )).reshape(X1.shape),
    alpha= 0.75, cmap = ListedColormap(('red','green') ) )


plt.xlim(X1.min(), X1.max() )
plt.ylim(X2.min() ,X2.max() )    


for i,j in enumerate( np.unique(y_set)  ):
    plt.scatter( X_set[ y_set == j ,0  ], X_set[ y_set ==j ,1 ] , c = ListedColormap(('red', 'green'))(i), label = j )

plt.title('Logistic Regression (Test set)')
plt.xlabel('Age')    
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()