# IMPORT DATASET

In [254]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [236]:
dataset=pd.read_csv('data.csv')
X= dataset.iloc[:,:-1].values
y= dataset.iloc[:,-1].values

In [255]:
dataset.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [209]:
dataset['Age'].fillna(dataset['Age'].mean() , inplace=True)
dataset.isnull().sum()


Country      0
Age          0
Salary       1
Purchased    0
dtype: int64

In [189]:
dataset['Salary'].fillna( dataset['Salary'].mean() , inplace=True)
dataset.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [256]:
from sklearn.impute import SimpleImputer
import numpy as np 

imputer = SimpleImputer( missing_values = np.nan , strategy = 'mean' )


imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])





X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [268]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


ct = ColumnTransformer( transformers = [( 'encoder', OneHotEncoder() , [0] )] , remainder = 'passthrough'  )


np.array(ct.fit_transform(X))

array([[0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [263]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [191]:
dataset.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        10 non-null     float64
 2   Salary     10 non-null     float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [192]:
dataset.describe()

Age        Salary
count  10.000000     10.000000
mean   38.777778  63777.777778
std     7.253777  11564.099406
min    27.000000  48000.000000
25%    35.500000  55000.000000
50%    38.388889  62388.888889
75%    43.000000  70750.000000
max    50.000000  83000.000000

In [193]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [194]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [195]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# TAKING CARE OF MISSING VALUES


In [196]:
print(X)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# Encoding Categorical Data 
# Encoding the Independent Variable

In [198]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


# Encoding Categorical Data 
# Encoding the Dependent Variable

In [273]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y = np.array(le.fit_transform(y))
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [200]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


# Splitting the Dataset into the Training set and Test Set

In [201]:
from sklearn.model_selection  import train_test_split 

X_train , X_test , y_train , y_test  = train_test_split(X,y, test_size = 0.2 , random_state =1  )

In [202]:
print(X_train)

[[0.0 0.0 1.0 nan 52000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [203]:
print(X_test)


[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [204]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [205]:
print(y_test)

[0 1]


In [206]:
  import random

  random.seed(42)
  print(random.randint(1, 100))  # Always prints: 82
  print(random.randint(1, 100))  # Always prints: 15
  print(random.randint(1, 100))  # Always prints: 4

  random.seed(0)
  print(random.randint(1, 100))  # Always prints: 85
  print(random.randint(1, 100))  # Always prints: 63
  

82
15
4
50
98


In [282]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values


from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values =np.nan, strategy = 'mean')
imputer.fit(X[:,1:3])
x[:,1:3] = imputer.transform(X[:,1:3])


from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,LabelEncoder


ct = ColumnTransformer( transformers = [( 'encoder', OneHotEncoder(), [0]) ] , remainder = 'passthrough' )
ct.fit_transform(X)
X =np.array( ct.transform(X) )
y=np.array(le.fit_transform(y))